
// ============================================================
// PUJIVERSE NETWORK — Master Data
// ============================================================

const CHANNELS = [
  { sno:"1.01", name:"Pujiverse AI", handle:"@pujiverseai", cat:"Science & Technology", url:"https://www.youtube.com/@PUJIVERSE-NEWS", score:98, cpm:"Very High", team:2, status:"LIVE", playlists:["ChatGPT Mastery — Every Trick, Prompt & Hack for 2026","Top AI Tools of 2026 — Reviews, Comparisons & Free Alternatives","AI Agents & Automation — Replace Hours of Work with Smart Workflows","Make Money with AI — Proven Income Streams Using AI Tools","AI News Weekly — Every Major AI Update Explained Simply"] },
  { sno:"1.02", name:"PUJIVERSE TECH", handle:"@pujiversetech", cat:"Science & Technology", url:"https://www.youtube.com/@pujiversetech", score:89, cpm:"Very High", team:2, status:"LIVE", playlists:["iPhone vs Android — Honest Comparisons, Hidden Features & Winners","Budget vs Premium — ₹500 vs ₹50,000 Tech Challenges","Smartphone Hidden Features — Tricks Apple and Google Don't Advertise","Laptop Reviews — Best Laptops for Students, Gaming, Work & Creators","Smart Home & Accessories — Upgrade Your Setup for 2026"] },
  { sno:"1.03", name:"Pujiverse Future", handle:"@pujiversefuture", cat:"Science & Technology", url:"https://www.youtube.com/@pujiversefuture", score:86, cpm:"High", team:1, status:"LIVE", playlists:["2030 to 2050 — What the Future Really Looks Like","Flying Cars, Hyperloop & The Future of Transport","Robotics Revolution — Humanoid Robots Taking Over Work","Brain-Computer Interfaces — Neuralink & The End of Keyboards","Colonizing Mars & The Space Economy of 2030"] },
  { sno:"1.04", name:"Pujiverse Space", handle:"@pujiversespace", cat:"Science & Technology", url:"https://www.youtube.com/@pujiversespace", score:85, cpm:"High", team:1, status:"LIVE", playlists:["Black Holes & Cosmic Mysteries — What's Really Out There","Life on Other Planets — Aliens, Exoplanets & The Search for ET","NASA, SpaceX & ISRO — Every Space Mission Updated","Planets & Solar System — Everything You Never Learned in School","James Webb & Hubble — Photos That Broke Astronomy"] },
  { sno:"1.05", name:"Pujiverse Gadgets", handle:"@pujiversegadgets", cat:"Science & Technology", url:"https://www.youtube.com/@pujiversegadgets", score:83, cpm:"Very High", team:1, status:"LIVE", playlists:["Amazon Finds Under ₹500 — Gadgets That Feel Like Magic","Smart Home Gadgets That Change Daily Life","Weird Gadgets That Shouldn't Exist But Do","Kitchen Gadgets That Save Hours in the Kitchen","Gift Ideas for Every Occasion & Budget"] },
  { sno:"1.06", name:"Pujiverse Mystery", handle:"@pujiversemystery", cat:"Entertainment", url:"https://www.youtube.com/@pujiversemystery", score:97, cpm:"High", team:2, status:"LIVE", playlists:["Missing Persons Cases That Still Haunt the World","Unexplained Historical Mysteries — Events Science Can't Solve","Lost Civilizations & Ancient Mysteries","Cursed Places & Cursed Objects — Real Stories, Real Deaths","Cryptids & Real Monster Sightings Around the World"] },
  { sno:"1.07", name:"Pujiverse True Crime", handle:"@pujiversetruecrime", cat:"Entertainment", url:"https://www.youtube.com/@pujiversetruecrime", score:96, cpm:"High", team:2, status:"LIVE", playlists:["Serial Killers Who Shocked the World","Perfect Crimes That Almost Got Away","Cold Cases Finally Solved — DNA, Genealogy, and Justice Decades Later","Unsolved Murders That Still Haunt Investigators","Famous Con Artists & Billion-Dollar Scams"] },
  { sno:"1.08", name:"Pujiverse Psychology", handle:"@pujiversepsychology", cat:"Education", url:"https://www.youtube.com/@pujiversepsychology", score:95, cpm:"High", team:2, status:"LIVE", playlists:["Dark Psychology — Manipulation Tactics You Should Know","Read People Like a Book — Body Language & Behavior Analysis","Cognitive Biases & Why Your Brain Lies to You","Understanding Narcissists, Sociopaths & Psychopaths","Human Behavior Experiments That Changed Science"] },
  { sno:"1.09", name:"Pujiverse Conspiracy", handle:"@pujiverseconspiracy", cat:"Entertainment", url:"https://www.youtube.com/@pujiverseconspiracy", score:92, cpm:"Medium", team:1, status:"LIVE", playlists:["Conspiracy Theories That Turned Out to Be True","JFK, Moon Landing & Historical Conspiracies","Secret Societies — Illuminati, Freemasons, Skull and Bones","Big Pharma, Big Food & Corporate Cover-Ups","UFO Disclosure — Governments Finally Admitting Aliens?"] },
  { sno:"1.10", name:"Pujiverse Paranormal", handle:"@pujiverseparanormal", cat:"Entertainment", url:"https://www.youtube.com/@pujiverseparanormal", score:88, cpm:"Medium", team:1, status:"LIVE", playlists:["Most Haunted Places on Earth — Real Hauntings Documented","Real Ghost Encounters — Caught on Camera & Witness Accounts","Demonic Encounters, Possessions & Real Exorcisms","Near-Death Experiences & Life After Death","Paranormal Investigations — Ghost Hunters in Action"] },
  { sno:"1.11", name:"Pujiverse Science", handle:"@pujiversescience", cat:"Science & Technology", url:"https://www.youtube.com/@pujiversescience", score:90, cpm:"High", team:2, status:"LIVE", playlists:["Mind-Blowing Science Experiments You Can Do at Home","What Happens If... — Science Answers Your Wild Questions","Biology Secrets — How Your Body Really Works","Chemistry That Feels Like Magic — Reactions Explained","Dangerous Science — The Deadliest Chemicals, Animals & Phenomena"] },
  { sno:"1.12", name:"Pujiverse Finance", handle:"@pujiversefinance", cat:"Education", url:"https://www.youtube.com/@PujiVerseWealth", score:91, cpm:"Very High", team:2, status:"LIVE", playlists:["Passive Income Ideas — Make Money While You Sleep","Stock Market for Beginners — Start Investing in 2026","Personal Finance — Budget, Save, and Build Wealth on Any Income","How the Rich Think — Money Habits of Millionaires","Side Hustles That Actually Work — Earn ₹10K to ₹1L Extra Per Month"] },
  { sno:"1.13", name:"Pujiverse Business", handle:"@pujiversebusiness", cat:"Education", url:"https://www.youtube.com/@pujiversebusiness", score:87, cpm:"Very High", team:1, status:"LIVE", playlists:["From Zero to Crore — Indian Entrepreneur Success Stories","Business Ideas for 2026 — Low Investment, High Returns","Marketing Masterclass — Grow Any Business in 2026","How to Start a Startup — From Idea to Funded Company","Business Lessons from Billionaires — Elon, Ambani, Adani, Bezos"] },
  { sno:"1.14", name:"Pujiverse Crypto", handle:"@pujiversecrypto", cat:"Education", url:"https://www.youtube.com/@pujiversecrypto", score:85, cpm:"Very High", team:1, status:"LIVE", playlists:["Bitcoin Explained — From Basics to Halving, ETFs & 2026 Predictions","Ethereum & Altcoins That Could 10x in 2026","DeFi & Yield Farming — Earn Passive Income with Crypto","NFTs, Web3 & The Future of Digital Ownership","Crypto Scams, Rug Pulls & How to Protect Your Money"] },
  { sno:"1.15", name:"Pujiverse Real Estate", handle:"@pujiverserealestate", cat:"Education", url:"https://www.youtube.com/@pujiverserealestate", score:82, cpm:"Very High", team:1, status:"LIVE", playlists:["First-Time Home Buyer Guide — Buy Your First Home in India","Rental Property Investing — Build Passive Income with Real Estate","House Flipping — Buy Low, Renovate, Sell High","Luxury Real Estate Tours — Mansions, Penthouses & Dream Homes","Commercial Real Estate & REITs — Invest Without Buying Property"] },
  { sno:"1.16", name:"Pujiverse Luxury", handle:"@pujiverseluxury", cat:"Entertainment", url:"https://www.youtube.com/@pujiverseluxury", score:84, cpm:"High", team:1, status:"LIVE", playlists:["Inside Billionaire Homes — Mukesh Ambani, Elon Musk, Bill Gates","Supercars, Hypercars & Cars Money Alone Can't Buy","Private Jets & Mega Yachts — Travel Like a Billionaire","Most Expensive Things in the World","Luxury Brands Decoded — Rolex, Hermès, Louis Vuitton, Ferrari"] },
  { sno:"1.17", name:"Pujiverse Gaming", handle:"@pujiversegaming", cat:"Gaming", url:"https://www.youtube.com/@PujiverseGaming", score:93, cpm:"Medium", team:2, status:"LIVE", playlists:["Game Secrets — Easter Eggs Nobody Found for Years","Impossible Gaming Challenges — Beat the Game Without...","Top Games of 2026 — New Releases, Reviews & Hidden Gems","Mobile Gaming & BGMI — From Rookie to Pro","Gaming History — How Video Games Became the Biggest Industry"] },
  { sno:"1.18", name:"PUJIVERSE CINE", handle:"@pujiversemovies", cat:"Film & Animation", url:"https://www.youtube.com/@PUJIVERSECINE", score:87, cpm:"Medium", team:2, status:"LIVE", playlists:["Hollywood Movie Theories & Easter Eggs You Missed","Tollywood Films — Telugu Cinema Deep Dives & Legend Tributes","Bollywood Classics & Modern Hits — Films That Defined Generations","Movie Endings Explained — Every Confusing Climax Decoded","Korean, Japanese & World Cinema — Hidden Gems Beyond Hollywood"] },
  { sno:"1.19", name:"Pujiverse Sports", handle:"@pujiversesports", cat:"Sports", url:"https://www.youtube.com/@pujiversesports", score:86, cpm:"Medium", team:1, status:"LIVE", playlists:["Cricket Greatest Moments — World Cups, Records & Legends","Football (Soccer) — Messi, Ronaldo, World Cup & Champions League","NBA Basketball — LeBron, Jordan, Curry & Greatest Games","F1 Racing, MMA & Combat Sports — Ultimate Athletic Drama","Olympics & Athletics — India's Rising Stars and Global Glory"] },
  { sno:"1.20", name:"Pujiverse Celebrity", handle:"@pujiversecelebrity", cat:"Entertainment", url:"https://www.youtube.com/@pujiversecelebrity", score:89, cpm:"Medium", team:1, status:"LIVE", playlists:["Bollywood Celebrity Lives — Scandals, Rises & Untold Stories","Hollywood Rise & Fall Stories — Johnny Depp, Britney, Whitney","Tollywood Stars — Prabhas, Mahesh Babu, Allu Arjun Journey","K-Pop Phenomenon — BTS, BLACKPINK, Global Korean Wave","Influencer & Creator Empire — MrBeast, CarryMinati, Ranveer Allahbadia"] },
  { sno:"1.21", name:"PujiVerse Beatz", handle:"@pujiversebeatz", cat:"Music", url:"https://www.youtube.com/@PujiVerseBeatz", score:81, cpm:"Low", team:1, status:"LIVE", playlists:["Song Meanings & Lyrics Decoded — Songs You Misunderstood","Best Music of Every Genre — Pop, Rock, Hip-Hop, Classical, Indian","AI Music Creation with Suno — How to Make Songs from Scratch","Music Legends — A.R. Rahman, SP Balu, Ilaiyaraaja & Global Greats","Best Movie Songs & Background Scores — Cinematic Music Magic"] },
  { sno:"1.22", name:"Pujiverse Mind", handle:"@pujiversemind", cat:"Education", url:"https://www.youtube.com/@PujiverseWisdom", score:92, cpm:"High", team:2, status:"LIVE", playlists:["Build Unstoppable Habits — Tiny Changes, Life-Changing Results","Stoic Philosophy — Ancient Wisdom for Modern Life","Productivity & Deep Work — Get More Done in Less Time","Mental Health & Emotional Mastery — Control Your Mind","Rich Mindset vs Poor Mindset — Mental Shifts for Wealth"] },
  { sno:"1.23", name:"Pujiverse Motivation", handle:"@pujiversemotivation", cat:"Education", url:"https://www.youtube.com/@pujiversemotivation", score:88, cpm:"Medium", team:1, status:"LIVE", playlists:["Best Motivational Speeches That Changed Lives","Rags to Riches Stories — From Nothing to Everything","Never Give Up — Comeback Stories That Inspire Millions","Discipline Over Motivation — Become Unstoppable","Daily Motivation — Morning Fuel to Start Your Day Strong"] },
  { sno:"1.24", name:"PUJIVERSE HISTORY", handle:"@pujiversehistory", cat:"Education", url:"https://www.youtube.com/@PUJIVERSEHISTORY", score:86, cpm:"Medium", team:1, status:"LIVE", playlists:["Ancient India — Maurya, Chola, Vijayanagara & Forgotten Empires","World Wars Explained — WW1, WW2, Causes, Key Battles, Aftermath","Brutal Rulers & Dictators — The Most Feared Leaders in History","Lost Civilizations — Indus, Maya, Sumerian, Egyptian Mysteries","Indian Freedom Struggle — Real Stories Beyond School Textbooks"] },
  { sno:"1.25", name:"Pujiverse Languages", handle:"@pujiverselanguages", cat:"Education", url:"https://www.youtube.com/@PujiverseLingo", score:79, cpm:"Medium", team:1, status:"LIVE", playlists:["Learn Spanish Fast — Beginner to Conversational in 90 Days","Learn Japanese — Anime, Manga & Travel Japanese","Learn Korean Fast — K-Pop, K-Drama & Daily Conversation","Indian Languages — Hindi, Telugu, Tamil, Bengali, Marathi","English Mastery — Fluency, Grammar & Perfect Pronunciation"] },
  { sno:"1.26", name:"PUJIVERSE KIDS", handle:"@pujiversekids", cat:"Education", url:"https://www.youtube.com/@Pujiversekids", score:83, cpm:"Medium", team:2, status:"LIVE", playlists:["ABC & 123 — Learn Letters, Numbers, Shapes & Colors","Kids Stories — Panchatantra, Moral Stories & Fairy Tales","Nursery Rhymes — Classic & Modern Songs for Little Ones","Fun Science for Kids — Amazing Experiments & Facts","Good Habits & Values for Kids — Life Lessons Through Fun"] },
  { sno:"1.27", name:"Pujiverse Fitness", handle:"@pujiversefitness", cat:"Howto & Style", url:"https://www.youtube.com/@PujiverseFit", score:85, cpm:"Medium", team:1, status:"LIVE", playlists:["30-Day Transformation Challenges — Real Results","Home Workouts — No Gym, No Equipment, Full Results","Gym Training — Beginner to Advanced Lifting Guide","Weight Loss & Fat Burn — Science-Backed Methods That Work","Nutrition & Diet — Indian Bodybuilder & Fitness Meals"] },
  { sno:"1.28", name:"Pujiverse Recipes", handle:"@pujiverserecipes", cat:"Howto & Style", url:"https://www.youtube.com/@PujiverseFood", score:84, cpm:"Medium", team:1, status:"LIVE", playlists:["South Indian Recipes — Dosa, Idli, Sambar, Biryani & More","North Indian Recipes — Butter Chicken, Naan, Chole & Dal Makhani","American & Italian Classics — Pizza, Pasta, Burgers at Home","Chinese, Thai & Asian Recipes — Restaurant-Style at Home","Street Food from Around the World — India, Mexico, Thailand"] },
  { sno:"1.29", name:"Pujiverse LifeStyle", handle:"@pujiverselifestyle", cat:"People & Blogs", url:"https://www.youtube.com/@PujiverseVlogs", score:80, cpm:"Medium", team:1, status:"LIVE", playlists:["Morning Routines — 5AM Club, Miracle Morning, Billionaire Routines","Minimalism & Decluttering — Own Less, Live More","Aesthetic Daily Life — Cozy Routines, Study Vibes, Soft Living","Home Organization & Interior Design on a Budget","Self-Care Rituals — Mental, Physical & Emotional Wellness"] },
  { sno:"1.30", name:"Pujiverse Devotional", handle:"@pujiversedevotional", cat:"People & Blogs", url:"https://www.youtube.com/@PujiverseDevotional", score:77, cpm:"Medium", team:1, status:"LIVE", playlists:["Lord Shiva — Bhajans, Mantras & Stories of Mahadev","Lord Krishna — Bhagavad Gita, Bhajans & Divine Leelas","Lord Ganesha, Lord Hanuman & Beloved Hindu Deities","Divine Mothers — Durga, Lakshmi, Saraswati & Kali","Lord Venkateswara, Sai Baba & Lord Rama Devotional"] },
  { sno:"1.31", name:"Pujiverse Shorts", handle:"@pujiverseshorts", cat:"People & Blogs", url:"https://www.youtube.com/@pujiverseshorts", score:94, cpm:"High", team:2, status:"LIVE", playlists:["Mind-Blowing Facts in 60 Seconds — Daily Dose of Wow","Best Moments from Every Pujiverse Channel","Life Hacks That Actually Work — 60-Second Upgrades","Viral Moments & Trending Topics — What's Hot Right Now","Quick Motivation & Inspiration Clips — 60 Seconds to Fire You Up"] },
  { sno:"1.32", name:"Pujiverse Ocean", handle:"@pujiverseocean", cat:"Pets & Animals", url:"https://www.youtube.com/@pujiverseocean", score:85, cpm:"High", team:1, status:"LIVE", playlists:["Sharks — The Ocean's Most Feared & Misunderstood Predators","Whales, Dolphins & Intelligent Sea Mammals","Deep Sea Monsters — Creatures from the Ocean's Darkest Depths","Coral Reefs & Colorful Tropical Fish Explored","Aquariums, Aquascaping & Pet Fish Care Guide"] },
  { sno:"1.33", name:"Pujiverse Aviation", handle:"@pujiverseaviation", cat:"Autos & Vehicles", url:"https://www.youtube.com/@pujiverseaviation", score:86, cpm:"High", team:1, status:"LIVE", playlists:["Commercial Aircraft — Boeing vs Airbus, A380, 787 Dreamliner","Private Jets & Luxury Aviation — Inside the World of the Ultra-Rich","Aviation History — Greatest Flights, Crashes & Turning Points","Pilot Life, Cockpit Secrets & Airport Facts You Never Knew","Military Aircraft & Fighter Jets — The Most Powerful Flying Machines"] },
  { sno:"1.34", name:"Pujiverse Agriculture", handle:"@pujiverseagriculture", cat:"Pets & Animals", url:"https://www.youtube.com/@pujiverseagriculture", score:88, cpm:"Medium", team:1, status:"LIVE", playlists:["Organic Gardening & Home Farming — Grow Food at Home","Livestock & Dairy Farming — Complete Business Guide","Agri-Business Ideas — Start a Farming Startup in 2026","Sustainable Living & Permaculture Practices","Technology in Farming — Drones, AI & Smart Agriculture"] },
  { sno:"1.35", name:"Pujiverse Transport", handle:"@pujiversetransport", cat:"Autos & Vehicles", url:"https://www.youtube.com/@pujiversetransport", score:78, cpm:"Medium", team:1, status:"LIVE", playlists:["World's Greatest Trains — Bullet Trains, Luxury Rails & Indian Railways","Electric Vehicles & Green Transport — The Future of Mobility","Ships, Cargo & Maritime Transport — Giants of the Sea","Mega Infrastructure — Bridges, Tunnels, Highways & Engineering Marvels","Road Trips, Classic Cars & Motorbike Culture"] },
  { sno:"1.36", name:"Pujiverse Life Hacks", handle:"@pujiverselifehacks", cat:"Howto & Style", url:"https://www.youtube.com/@pujiverselifehacks", score:82, cpm:"High", team:1, status:"LIVE", playlists:["Kitchen Hacks That Save Time, Money & Effort Every Day","Cleaning Hacks for Every Room — Spotless Home in Minutes","Money-Saving Hacks — Spend Less Without Sacrificing Quality","DIY Fixes & Creative Problem Solving at Home","Phone & Tech Hacks That Save Hours Every Week"] },
  { sno:"1.37", name:"Pujiverse Music", handle:"@pujiversemusic", cat:"Music", url:"https://www.youtube.com/@pujiversemusic", score:80, cpm:"Medium", team:1, status:"LIVE", playlists:["Song Meanings & Lyrics Decoded — Songs You Misunderstood","Best Music of Every Genre — Pop, Rock, Hip-Hop, Classical, Indian","AI Music Creation with Suno — How to Make Songs from Scratch","Music Legends — A.R. Rahman, SP Balu, Ilaiyaraaja & Global Greats","Best Movie Songs & Background Scores — Cinematic Music Magic"] }
];

const SOCIAL_LINKS = [
  { platform:"YouTube",    icon:"yt",  handle:"@pujiverse",           url:"https://www.youtube.com/@PUJIVERSE-NEWS",               color:"#ff0000" },
  { platform:"Instagram",  icon:"ig",  handle:"@pujiverseofficial",   url:"https://www.instagram.com/pujiverseofficial",            color:"#e1306c" },
  { platform:"TikTok",     icon:"tt",  handle:"@pujiverse",           url:"https://www.tiktok.com/@pujiverse",                     color:"#69c9d0" },
  { platform:"X (Twitter)",icon:"x",   handle:"@pujiverse",           url:"https://twitter.com/pujiverse",                         color:"#ffffff" },
  { platform:"Facebook",   icon:"fb",  handle:"/PUJIVERSEOFFICIAL",   url:"https://www.facebook.com/PUJIVERSEOFFICIAL/",            color:"#1877f2" },
  { platform:"LinkedIn",   icon:"li",  handle:"/in/pujiverse-pujith", url:"https://linkedin.com/in/pujiverse-pujith",               color:"#0a66c2" },
  { platform:"Pinterest",  icon:"pi",  handle:"@pujiverse",           url:"https://pinterest.com/pujiverse",                       color:"#e60023" },
  { platform:"Medium",     icon:"me",  handle:"@pujiverse",           url:"https://medium.com/@pujiverse",                         color:"#02b875" },
  { platform:"Substack",   icon:"ss",  handle:"@pujiverse",           url:"https://substack.com/@pujiverse",                       color:"#ff6719" },
  { platform:"Discord",    icon:"dc",  handle:"pujiverse",            url:"https://discord.gg/pujiverse",                          color:"#5865f2" },
  { platform:"WhatsApp",   icon:"wa",  handle:"Chat with us",         url:"https://wa.me/message/HPIAGRGKO23SM1",                  color:"#25d366" },
  { platform:"Quora",      icon:"qu",  handle:"Pujiverse",            url:"https://www.quora.com/profile/Pujiverse",                color:"#b92b27" },
  { platform:"Dailymotion",icon:"dm",  handle:"PUJIVERSE",            url:"https://www.dailymotion.com/PUJIVERSE",                 color:"#00aaff" },
];

const CAT_COLORS = {
  "Science & Technology": { bg:"oklch(0.22 0.06 220)", accent:"#22d3ee", badge:"#0e7490" },
  "Entertainment":        { bg:"oklch(0.22 0.06 290)", accent:"#c084fc", badge:"#7e22ce" },
  "Education":            { bg:"oklch(0.22 0.06 250)", accent:"#818cf8", badge:"#4338ca" },
  "Gaming":               { bg:"oklch(0.22 0.06 145)", accent:"#4ade80", badge:"#15803d" },
  "Music":                { bg:"oklch(0.22 0.06 340)", accent:"#f472b6", badge:"#be185d" },
  "Sports":               { bg:"oklch(0.22 0.06 50)",  accent:"#fb923c", badge:"#c2410c" },
  "Film & Animation":     { bg:"oklch(0.22 0.06 20)",  accent:"#f87171", badge:"#b91c1c" },
  "Howto & Style":        { bg:"oklch(0.22 0.06 80)",  accent:"#facc15", badge:"#a16207" },
  "People & Blogs":       { bg:"oklch(0.22 0.06 310)", accent:"#a78bfa", badge:"#6d28d9" },
  "Pets & Animals":       { bg:"oklch(0.22 0.06 175)", accent:"#34d399", badge:"#065f46" },
  "Autos & Vehicles":     { bg:"oklch(0.22 0.06 65)",  accent:"#fbbf24", badge:"#92400e" },
};

const ALL_CATEGORIES = ["All", ...Array.from(new Set(CHANNELS.map(c => c.cat)))];
